// Experiences Popups
let popup = document.getElementById("popup");
function openPopup0(){
    document.getElementById('popup').scrollIntoView();
    popup.classList.add("open-popup");
    document.getElementById('predictions').innerHTML = "<table><tr><td>Home Team</td><td>Away Team</td><td>Home Score</td><td>Away Score</td><td>Home Win</td></tr><tr><td>BAL</td><td>CLE</td><td>26</td><td>20</td><td>75.9%</td></tr><tr><td>LV</td><td>LAC</td><td>20</td><td>24</td><td>43.0%</td></tr><tr><td>PIT</td><td>CIN</td><td>24</td><td>20</td><td>73.9%</td></tr><tr><td>ATL</td><td>CAR</td><td>23</td><td>20</td><td>80.1%</td></tr><tr><td>DEN</td><td>KC</td><td>20</td><td>25</td><td>32.0%</td></tr><tr><td>LA</td><td>SEA</td><td>24</td><td>23</td><td>54.8%</td></tr><tr><td>TEN</td><td>HOU</td><td>22</td><td>24</td><td>24.9%</td></tr><tr><td>PHI</td><td>NYG</td><td>24</td><td>20</td><td>90.4%</td></tr><tr><td>IND</td><td>JAX</td><td>23</td><td>21</td><td>67.0%</td></tr><tr><td>DET</td><td>MIN</td><td>27</td><td>22</td><td>75.9%</td></tr><tr><td>DAL</td><td>WAS</td><td>25</td><td>26</td><td>73.9%</td></tr><tr><td>ARI</td><td>SF</td><td>23</td><td>24</td><td>26.6%</td></tr><tr><td>GB</td><td>CHI</td><td>22</td><td>18</td><td>78.5%</td></tr><tr><td>NYJ</td><td>MIA</td><td>21</td><td>22</td><td>29.5%</td></tr><tr><td>TB</td><td>NO</td><td>21</td><td>20</td><td>63.0%</td></tr><tr><td>NE</td><td>BUF</td><td>19</td><td>21</td><td>10.8%</td></tr></table>";
}
function openPopup1(){
    document.getElementById('popup').scrollIntoView();
    popup.classList.add("open-popup");
    document.getElementById('predictions').innerHTML = "<table><tr><td>Home Team</td><td>Away Team</td><td>Home Score</td><td>Away Score</td><td>Home Win</td></tr><tr><td>PIT</td><td>KC</td><td>19</td><td>20</td><td>43.5%</td></tr><tr><td>HOU</td><td>BAL</td><td>22</td><td>23</td><td>42.1%</td></tr><tr><td>CHI</td><td>SEA</td><td>23</td><td>24</td><td>34.6%</td></tr><tr><td>WAS</td><td>ATL</td><td>25</td><td>20</td><td>50.4%</td></tr><tr><td>NE</td><td>LAC</td><td>19</td><td>20</td><td>30.4%</td></tr><tr><td>CIN</td><td>DEN</td><td>26</td><td>20</td><td>54.5%</td></tr><tr><td>NYG</td><td>IND</td><td>19</td><td>23</td><td>30.5%</td></tr><tr><td>LA</td><td>ARI</td><td>24</td><td>22</td><td>75.6%</td></tr><tr><td>TB</td><td>CAR</td><td>22</td><td>20</td><td>86.0%</td></tr><tr><td>BUF</td><td>NYJ</td><td>26</td><td>17</td><td>87.6%</td></tr><tr><td>MIN</td><td>GB</td><td>23</td><td>21</td><td>51.4%</td></tr><tr><td>NO</td><td>LV</td><td>23</td><td>19</td><td>66.3%</td></tr><tr><td>JAX</td><td>TEN</td><td>25</td><td>19</td><td>62.5%</td></tr><tr><td>PHI</td><td>DAL</td><td>25</td><td>24</td><td>69.7%</td></tr><tr><td>CLE</td><td>MIA</td><td>21</td><td>25</td><td>45.9%</td></tr><tr><td>SF</td><td>DET</td><td>23</td><td>24</td><td>33.4%</td></tr></table>";
}
function openPopup2(){
    document.getElementById('popup').scrollIntoView();
    popup.classList.add("open-popup");
    document.getElementById('predictions').innerHTML = "<table><tr><td>Home Team</td><td>Away Team</td><td>Home Score</td><td>Away Score</td><td>Home Win</td></tr><tr><td>LAC</td><td>DEN</td><td>20</td><td>21</td><td>43.6%</td></tr><tr><td>KC</td><td>HOU</td><td>22</td><td>21</td><td>70.7%</td></tr><tr><td>BAL</td><td>PIT</td><td>26</td><td>20</td><td>60.6%</td></tr><tr><td>BUF</td><td>NE</td><td>26</td><td>19</td><td>92.2%</td></tr><tr><td>ATL</td><td>NYG</td><td>23</td><td>20</td><td>71.0%</td></tr><tr><td>CHI</td><td>DET</td><td>23</td><td>24</td><td>14.7%</td></tr><tr><td>CAR</td><td>ARI</td><td>21</td><td>24</td><td>34.7%</td></tr><tr><td>NYJ</td><td>LA</td><td>21</td><td>22</td><td>30.7%</td></tr><tr><td>WAS</td><td>PHI</td><td>25</td><td>25</td><td>21.0%</td></tr><tr><td>CIN</td><td>CLE</td><td>26</td><td>20</td><td>51.1%</td></tr><tr><td>IND</td><td>TEN</td><td>23</td><td>19</td><td>73.8%</td></tr><tr><td>SEA</td><td>MIN</td><td>23</td><td>22</td><td>50.5%</td></tr><tr><td>LV</td><td>JAX</td><td>21</td><td>24</td><td>50.0%</td></tr><tr><td>MIA</td><td>SF</td><td>27</td><td>23</td><td>49.8%</td></tr><tr><td>DAL</td><td>TB</td><td>24</td><td>25</td><td>61.1%</td></tr><tr><td>GB</td><td>NO</td><td>22</td><td>21</td><td>71.9%</td></tr></table>";
}

function openPopup3(){
    document.getElementById('popup').scrollIntoView();
    popup.classList.add("open-popup");
    document.getElementById('predictions').innerHTML = "<table><tr><td>Home Team</td><td>Away Team</td><td>Home Score</td><td>Away Score</td><td>Home Win</td></tr><tr><td>SF</td><td>LA</td><td>24</td><td>22</td><td>60.6%</td></tr><tr><td>NO</td><td>WAS</td><td>26</td><td>23</td><td>60.4%</td></tr><tr><td>CLE</td><td>KC</td><td>20</td><td>25</td><td>27.3%</td></tr><tr><td>TEN</td><td>CIN</td><td>24</td><td>24</td><td>38.8%</td></tr><tr><td>HOU</td><td>MIA</td><td>23</td><td>21</td><td>57.5%</td></tr><tr><td>NYG</td><td>BAL</td><td>19</td><td>23</td><td>14.7%</td></tr><tr><td>JAX</td><td>NYJ</td><td>25</td><td>17</td><td>59.8%</td></tr><tr><td>CAR</td><td>DAL</td><td>23</td><td>24</td><td>15.2%</td></tr><tr><td>LAC</td><td>TB</td><td>21</td><td>24</td><td>45.1%</td></tr><tr><td>DEN</td><td>IND</td><td>25</td><td>23</td><td>59.3%</td></tr><tr><td>ARI</td><td>NE</td><td>24</td><td>19</td><td>67.9%</td></tr><tr><td>DET</td><td>BUF</td><td>27</td><td>21</td><td>62.9%</td></tr><tr><td>PHI</td><td>PIT</td><td>24</td><td>20</td><td>63.4%</td></tr><tr><td>SEA</td><td>GB</td><td>22</td><td>23</td><td>47.3%</td></tr><tr><td>MIN</td><td>CHI</td><td>21</td><td>18</td><td>76.3%</td></tr><tr><td>LV</td><td>ATL</td><td>24</td><td>20</td><td>44.1%</td></tr></table>";
}

function openPopup4(){
    document.getElementById('popup').scrollIntoView();
    popup.classList.add("open-popup");
    document.getElementById('predictions').innerHTML = '<table><tr><td>Home Team</td><td>Away Team</td><td>Home Score</td><td>Away Score</td><td>Home Win</td></tr><tr><td>DET</td><td>GB</td><td>27</td><td>23</td><td>73.5%</td></tr><tr><td>PIT</td><td>CLE</td><td>21</td><td>20</td><td>71.1%</td></tr><tr><td>NYG</td><td>NO</td><td>19</td><td>22</td><td>35.3%</td></tr><tr><td>MIA</td><td>NYJ</td><td>27</td><td>17</td><td>77.5%</td></tr><tr><td>TEN</td><td>JAX</td><td>21</td><td>24</td><td>46.4%</td></tr><tr><td>MIN</td><td>ATL</td><td>21</td><td>20</td><td>70.8%</td></tr><tr><td>PHI</td><td>CAR</td><td>24</td><td>20</td><td>93.9%</td></tr><tr><td>TB</td><td>LV</td><td>22</td><td>19</td><td>73.6%</td></tr><tr><td>ARI</td><td>SEA</td><td>23</td><td>24</td><td>31.9%</td></tr><tr><td>SF</td><td>CHI</td><td>24</td><td>18</td><td>77.9%</td></tr><tr><td>LA</td><td>BUF</td><td>21</td><td>24</td><td>35.6%</td></tr><tr><td>KC</td><td>LAC</td><td>21</td><td>20</td><td>82.6%</td></tr><tr><td>DAL</td><td>CIN</td><td>25</td><td>24</td><td>68.1%</td></tr></table>';
}